### ISSUE TITLE
Refactoring Stisla 

### ISSUE THREAD

**Issue by nauvalazhar** [stisla/stisla#154]
It has been more than 1 year since Stisla v2. I am glad this project can help your work faster, on the other hand I am also disappointed with the documentation that I wrote. So, I hope this refactor can be better than the previous version.

I have an idea in mind, one of which is making Stisla available on several frameworks, we can use Web Components (as suggested by @cyberhck). Or we can port it one by one, I don't know which way is more efficient.

I've been working on several projects lately using Tailwind, it's been a pleasant experience. But, to use it as a template base, I have to think again - I have to think about the architecture.

Bootstrap 5 release date is still unclear - looking at the repository seems like it won't be long. But, we never know when, this is what kept me from using the current Bootstrap version (4.x).

For this refactor, I focus on template architecture, one of which I use the "theming" method, rather than the "override" method (the method I used before). So, users will find it easier to customize it. Also, I reduced the custom class, I added several utility classes, to allow creating custom components without having to write custom classes.

This isn't finished yet. I'm still confused about choosing a suitable color, but, here's a little preview that you can see:

![image](https://user-images.githubusercontent.com/14899175/78105046-78084100-741a-11ea-81bd-5f1d6b19f16f.png)

I need your advice. And if you have, give me a good template design reference in your opinion.

**Comment by tarikhagustia** [comment]
looks good, keep going ..

**Comment by TheRealLenon** [comment]
Is there anything new, about an React "Template"? Or are there any helpful tips & tricks, on how to implement it into an React Project?

**Comment by cyberhck** [comment]
it's a little hard to say with react, there are not just 1 issues currently,

stisla uses bootstrap, and while bootstrap is popular, it uses jQuery, and jQuery is not declarative, where react is, jQuery simply doesn't play nice with React.

Now there are other ways, there's a reactstrap and other variants of bootstrap, or you could also just as well not include jQuery and a lot of UI would work except some functionality,

another thing is stisla does use the bootstrap variables, but there are a lot of other custom css as well, which is fine, but usage of jQuery will be something to watch out for.

On refactoring stisla I can invision something like this:
- use TypeStyle to do all stylings which means you'll have 1 styling npm package,
- while doing styling package, we'd have to think about being able to overwrite themes (I can expand on this part a lot more if you are ever interested)
- Once styling package is there and because it's just JavaScript package, all you have to do is import the theme provider and use it on separate project which would be components project. this components project could be either generated or hand written (probably the latter), and you wouldn't have to install anything except this components project.

Nice thing about components project would be it could be written for react, vue, angular or anything else,

But currently, there's nothing on the works, you can simply import and rely only on styles.

**Comment by cyberhck** [comment]
to think about it, I'd like to make a suggestion, let's not write css by hand, let's use typestyle, that way it's just javascript, can be server side rendered very easily, and you can import javascript package in any language.

**Comment by rizkyyangpalsu** [comment]
That's look good template. I think you don't need to use bootstrap and I agree with @cyberhck to use typestyle to easily write CSS

**Comment by nauvalazhar** [comment]
Hi @cyberhck , can you give a simple example? So I can get better visuals.

**Comment by cyberhck** [comment]
So I'd create a type called theme, and use that theme in css rules,
```typescript
type palette: "success" | "warning" | "danger" | "notice" | "neutral";
type spacing: "NONE" | "XS" | "S" | "M" | "L" | "XL" | "XXL" | "XXXL";
type border: "NONE" | "XS" | "S" | "M" | "L";
interface IntentValues {
    color: Color;
    background: Color;
    border: Color;
}
interface Theme {
    palette: Record<palette, IntentValues>;
    spacing: Record<spacing, IntentValues>;
    borderRadius: Record<border, IntentValues>;
}
```
That'd be your core theme type (of course it will have some more values, this is just an example), and you'll have another value, which basically looks like the following (I don't know what name could it be yet):

```typescript
interface ComponentValues {
    input: {
        padding: string; // eg: (M XXL)
        variants: Record<palette, IntentValues>;
    },
    card: {
        padding: string; // obviously card will have multiple variant, big, small and large, each of them will have their own padding, width values etc,
    },
    span: {
        variant: {
             strong: Record<palette, IntentValues>;
             light: Record<palette, IntentValues>;
             neutral: Record<palette, IntentValues>;
        }
    },
    paragraph: {},
    heading: {},
    alert: {}
}
```
So for example, if I wanted to use span in a page, I'd simply do:
```typescript
// at the beginning of app, all themes are initialized,

// when I need to use span:
<Span variant="success" weight="light">some description</Span>
```

and that's it, kinda like tailwind, but it's themeable on runtime, you can have 2 theme and on runtime select anything you want.

Also because typestyle is just javascript object, it's a really small footprint, and it can be imported in any javascript project no need for css or scss loaders, simply import our theme, and that's it.

**Comment by cyberhck** [comment]
while this is really clean and maintainable, having a separate theme package and styles package will mean it'll be really easy to change values and maintain, but I must admit, it's no easy work, a lot of effort will have to be put on this,

also, creating styles might be the end for phase 1, but we still need to now create components specifically for vuejs, react and angular, BUT I don't think that's a very difficult thing, once we have the styles, creating components is basically very simple, while writing styles, I'll create a separate project where you can test and see how your styles look like visually, once you make a release on styles (which will include all screenshots of all variant), I can then write those components and someone else can write for vue and another one can write for angular following the exact same thing,

if some javascript logic can be extracted to package, that can also stay in our non-core theme package, (we can have, stisla-core, stisla-styles, stisla-react, stisla-vue, stisla-angular packages),

I can setup automatic release using semantic-release so we do release very often, so almost as soon as you create styles, I can try to keep up with react package.

**Comment by nauvalazhar** [comment]
Cool, really interesting. We will make it with web components? Maybe like you said, after that we need to make components for React, Vue or Angular. But, if there is already one example created, everything can run easily.

This will be better, because we don't depend on any framework. Also, it's easier, because everything is written with JavaScript.

There is a little that I don't understand, but it's only a technical matter that we can talk about later.

Maybe we next need to talk about the architecture of this project, such as folder structure, design patterns, or something. Because my experience of project architecture is not good, it is difficult to maintain.

**Comment by cyberhck** [comment]
web components is tricky, the problem with web components is that it's imperative, where as react, vuejs, angularjs, all are declarative, also, we don't really need to do anything though,

once you have styling, it's like you already have included css, all you need to do is use that css,

like this:
```tsx
const secondaryButton = theme.button.secondary;
<button className={secondaryButton}>Click me</button>
```
should be same in vue, angular as well :)

I can take care of making project architecture, setting up automatic release, but first we need the XD/sketch style guide.

**Comment by rizkyyangpalsu** [comment]
How @nauvalazhar ? The Bootstrap v5.0 alpha has arrived.

https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/

Stisla still using bootstrap or Stisla build own components?

**Comment by nauvalazhar** [comment]
Good idea to make our own components. But, that will make users have to relearn. If we use Bootstrap, who doesn't know Bootstrap? So, maybe I'll think about it first.

**Comment by cyberhck** [comment]
IMO: there's nothing to relearn if we use tools and provide tools correctly.

Example, say we have react library, and we wrote that library in typescript, even if other devs don't use typescript, they will get a lot of intellisense from most IDEs making them not having to learn at all, I've been using so many libraries but I still don't know which parameter is which where is something etc, I'm helped by my IDE and that's what development is supposed to look like anyway :)

**Comment by nauvalazhar** [comment]
Still, you have to learn again, even if you are helped by the IDE - although there isn't much to learn. I mean, when we use Bootstrap, developers will think, "oh, Bootstrap, I know that." It is very possible for us to create new ideas, one of which is to make the components ourselves, but we can make them in a separate repository.

**Comment by cyberhck** [comment]
the problem I see with bootstrap is lack of proper theming, If you had light and dark theme for example, it wastes so much of css space by creating 2 stylesheets,

What I'd want is just change the variables, and colors gets changed, but everything else which is re-usable, gets re-used.

Another side benefit is that if you import button component, then you don't import navbar's css, but only button's css.

That way you only import css which you need instead of importing everything.

**Comment by DayoWong0** [comment]
how about upgrade stisla with bootstrap 5 current in beta 2，it will make it easy to use in vue react  or angular framework
