### ISSUE TITLE
#suggestion Can you make tabs more beautiful? 

### ISSUE THREAD

**Issue by vimalmistry** [stisla/stisla#158]
I think stisla admin is most beutiful admin panel, but I thinks tabs design can be improved.
Current tab 
![Screenshot 2020-04-28 at 12 07 03 AM](https://user-images.githubusercontent.com/3993163/80408220-767c4c80-88e4-11ea-8838-5b564e95343c.png)

to something like.

![Screenshot 2020-04-28 at 12 07 55 AM](https://user-images.githubusercontent.com/3993163/80408451-d3780280-88e4-11ea-9c09-f28b110a7375.png)

Thanks

**Comment by polynar** [comment]
I think too, but I don't agree with your suggestion, the design you suggest I don’t think is clear that they are tabs, more like a menu bar. Yes, I think it can be improved, but so that it remains recognizable.
Like: (Sorry for the long comment)
![image](https://user-images.githubusercontent.com/1795922/80419529-9b1ef700-88d9-11ea-8fa3-5ebd7d5db152.png)
![image](https://user-images.githubusercontent.com/1795922/80419636-c9043b80-88d9-11ea-8278-1ae03289445e.png)
![image](https://user-images.githubusercontent.com/1795922/80419668-d7eaee00-88d9-11ea-8eff-82d4485fc875.png)
![image](https://user-images.githubusercontent.com/1795922/80419800-12ed2180-88da-11ea-9f53-a1145fdadb0d.png)
![image](https://user-images.githubusercontent.com/1795922/80419916-3adc8500-88da-11ea-953c-4dfa41b059e5.png)

**Comment by nauvalazhar** [comment]
Thank you for your suggestion. I'm glad if someone makes a pull request about this.

**Comment by Harshal96** [comment]
@nauvalazhar working on this.
