### ISSUE TITLE
Components in sidebar return - Not Found  The requested URL was not found on this server.

### ISSUE THREAD

**Issue by Serge-source** [stisla/stisla#168]
I have tried to install this awesome dashboard and succeeded to show the main page however  I am stuck when selecting a component from the sidebar to view. All components give the "Not Found error The requested URL was not found on this server.

I am pretty sure it may be a simple config tweak but I am slowly loosing my hair.

I would greatly appreciate some feedback to make this dashboard work like the demo.

Btw, thank you awesome work!

Thank you,

Serge

**Comment by zhanang19** [comment]
Hello Serge, I think it just a trailing slash issue in your url. If you just clone this repository and open up on your browser, make sure the url are `pages/` or `pages/index.html` instead of `pages`

For more info, please refer to [this article](https://en.ryte.com/wiki/Trailing_Slashes). Hope this will answer your question.
