### ISSUE TITLE
How to change modal content with ajax?

### ISSUE THREAD

**Issue by xubirula** [stisla/stisla#186]
I noticed the function fires on page load and set the body with the designed form component. The thing is, what when I want to change the body dinamicaly loading a page with ajax?

I tried using normal bootstrap modal but it gets all messed up due the fireModal function.

**Comment by gieart87** [comment]
@xubirula Yeah, I got a similar issue when trying to load the prefilled (data from ajax GET) form on modal. I was guessed that I can do this in the `shown' method but in fact, it's not being executed when the modal is shown. Hope anyone else can have a solution for this.

**Comment by gieart87** [comment]
@xubirula I've just tried that we can manipulate the modal content inside the 'created' method using the data from ajax. Actually, it's a bad solution since we will have multiple ajax calls depend on the number of modals on a particular page. But, at least it works. Look at my codes below:

<img width="921" alt="Screen Shot 2021-03-17 at 00 01 34" src="https://user-images.githubusercontent.com/145084/111350586-d7577380-86b4-11eb-9a3e-6dc465fa620c.png">
