### ISSUE TITLE
Does it support right to left?

### ISSUE THREAD

**Issue by OmidAhmadyani** [stisla/stisla#29]
if this theme support right to left(rtl) its very good buy if not i can do it!

**Comment by nauvalazhar** [comment]
Some time ago someone made RTL, but, it didn't cover the whole page and there were still a few bugs. You can see it [here](https://github.com/stisla/stisla/tree/master/dev/rtl).

But, if you can do it better, then do it and don't forget to document it :)

I hope you do it with an existing template engine. So that all HTML pages have the same [code base](https://github.com/stisla/stisla/tree/master/pages).

**Comment by khanzadimahdi** [comment]
i will complete the whole pages it in next a few days.

**Comment by fzn0x** [comment]
https://github.com/stisla/stisla/pull/10

I think it's added already
