### ISSUE TITLE
About color

### ISSUE THREAD

**Issue by jyxjjj** [stisla/stisla#49]
Oh.
Don't you think it is too bright?
Too white.
Make some blue? Red? Yello?
etc.?
I saw another template AdminLTE, its 3.0 dev version updated so slow so i found stisla.
But I think stisla should learn from it about its colors.
White is too harsh. ( Or "dazzling"? I am so sorry for my poor English.)

**Comment by philiplambok** [comment]
Yeah, I have the same concern about this, especially the green (_success_) color.

**Comment by nauvalazhar** [comment]
Hi, thank you for reporting the issue. Do you have good references for this? I will start working on this.

**Comment by jyxjjj** [comment]
>> I saw another template AdminLTE, its 3.0 dev version updated so slow so i found stisla.
> 
>> But I think stisla should learn from it about its colors.

As i said, you may learn the color of AdminLTE 3.0.

> If you want.

And I just think the sidebar and background were too bright, not others.

> You used:
> background-color: #000000;
> or background-color: transparent;
> or unset.

I think it is good to use:
#363F48 (My choice. I used it for my maintenance page.)
![363F48](https://img.shields.io/badge/363F48-363F48.svg)
Or #ECF0F5 (From AdminLTE 2.4)
![ECF0F5](https://img.shields.io/badge/ECF0F5-ECF0F5.svg)
Or #F4F6F9 (From AdminLTE 3)
![F4F6F9](https://img.shields.io/badge/F4F6F9-F4F6F9.svg)
Or #343A40 (From AdminLTE 3).
![343A40](https://img.shields.io/badge/343A40-343A40.svg)

> Color picture may be small, may cause aberration, you should test in CSS.

**Comment by nauvalazhar** [comment]
A few weeks ago, someone made a pull request (#35) to change the contrast so it wasn't too bright. 
![Screenshot_121](https://user-images.githubusercontent.com/14899175/55058142-bba8cc00-509d-11e9-9207-0e886abe2dfd.png)

And since version 2.1 I tried to swap the colors of the sidebar and navbar.
![Screenshot_122](https://user-images.githubusercontent.com/14899175/55058236-fca0e080-509d-11e9-966f-aaf751ecd333.png)

**Comment by jyxjjj** [comment]
So, what's your plan now?
And I don't think one color can make everyone like it.
You can use cache like "localStorage" to save themes of different colors.
I think it's really worth learning AdminLTE, it provides many colors and css classes.
And save to localStorage can let users choose their favourite theme.
Eg., I don't like purple-blue, I like sky-blue.

**Comment by nauvalazhar** [comment]
I don't think about making other skin colors. It makes me slow to do something else. I will focus on something else, like documentation, and add other features.

**Comment by Agungkes** [comment]
It's very great template so far. The color isn't not too brigth for me now.
And sure, more color is awesome.

-----
Keren bro tema nya ^^ ditambahin aja saran bro kalau mau kontribusi di sini sama issues template biar gak berantakan nanti pas issue nya banyak :D Good job

**Comment by nauvalazhar** [comment]
Thank you for the advice, @Agungkes :)

**Comment by stefanturcanu** [comment]
@nauvalazhar  now that it's open source ...maybe a new branch /dev with SCSS src files where we can make pull requests? 💡 🤔  

or at least to have the option to download src files to change our own theme. _find and replace_ can take you so far... 💪

**Comment by stefanturcanu** [comment]
> @nauvalazhar now that it's open source ...maybe a new branch /dev with SCSS src files where we can make pull requests? 💡 🤔
> 
> or at least to have the option to download src files to change our own theme. _find and replace_ can take you so far... 💪

my bad! just saw the releases 🙄 found the SCSS!

**Comment by cyberhck** [comment]
actually I've an idea which you might like.

Instead of changing color schemes, simply split your scss into parts, say you have input.scss, split into input.scss and input.theme.scss and the theme file should do color, but the actual color should come from variable file,

When you build it, make 2 build files, one normal file which has everything not related to colors, and include one which only includes themes.

Once built, it should generate style.css and one style.theme.scss this way we can have multi theme application.
